d4contacts/contactmanager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('appcontact.urls')),
    (r'^', include('appentity.urls')),
    (r'^', include('tasks.urls')),
    url(r'^admin/',include(admin.site.urls)),        
)

salespoint/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('sitio.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

sitio/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import *

urlpatterns = patterns('sitio.views',
                    url(r'^$','index',name='index'),
                    #url(r'^contacto$','contact_form',name='contact_form'),
                    url(r'^inicio$','inicio',name='inicio'),
                    url(r'^logout$','logoff',name='logoff'),
                    #url(r'^mycontacts','mycontacts',name='mycontacts'),
                    #url(r'^detailcontact/(?P<idc>\d+)/$','detailcontact',name='detailcontact'),
                    #url(r'^edtcontact/(?P<idc>\d+)/$','edtcontact',name='edtcontact'),
                    #url(r'^delcontact/(?P<idc>\d+)/$','delcontact',name='delcontact'),
                    #url(r'^resultados$','resultados',name='resultados'),
             ) 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += patterns('sitio.restviews',
    url(r'^login$','login',name='login'),
    #url(r'^addcontact$','addcontact',name='addcontact'),
    #url(r'^addphoto$','addphoto',name='addphoto'),
    #url(r'^delphoto/(?P<idu>\d+)/$','delphoto',name='delphoto'),
    #url(r'^location$','restlocation',name='restlocation'),
    #url(r'^addtag/$','addtag',name='addtag'),
    #url(r'^delnote$','delnote',name='delnote'),
    #url(r'^colonia$','colonia',name='colonia'),
    #url(r'^addnote$','addnote',name='addnote'),
    #url(r'^deltag$','deltag',name='deltag'),
    #url(r'^cps$','cps',name='cps'),
    
)

sitio/models.py
# -*- encoding: utf-8 -*-i
from django.db import models
from django.contrib.auth.models import User 

SALESPOINT_STATUS = (
        (1,'Activado'),
        (2,'Desactivado')
    )

CUSTOMER_STATUS = (
        ('1','Prospecto'),
        ('2','Cliente'),
        ('3','Comprador'),
        ('4','Extra')
    )


class SalesPoint(models.Model):
    class Meta:
        verbose_name = u'Punto de Venta'

    pointname = models.CharField(u'Punto de Venta',max_length=200)
    zipcode = models.CharField(u'C.P.',max_length=12)
    address = models.CharField(u'Calle/número',max_length=200)
    colonia = models.CharField(u'Colonia',max_length=200)
    delomun = models.CharField(u'Delegación/Municipio', max_length=200)
    state = models.CharField(u'Estado',max_length=200)
    status = models.BooleanField(default=1,choices=SALESPOINT_STATUS)
    poligon = models.TextField(blank=True,null=True)

    def __unicode__(self):
        return u'%s'%self.pointname



class Seller(models.Model):
    class Meta:
        verbose_name = u'Vendedores'
    salespoint = models.ForeignKey(SalesPoint)
    fullname = models.CharField(u'Nombre',max_length=200)
    birthdate = models.DateField(u'Fecha de Nacieminto')
    email = models.EmailField(u'eMail',max_length=254)
    phone = models.CharField(u'Tel.',max_length=20)
    sellerzipcode = models.CharField(u'C.P.',max_length=20)
    userid = models.ForeignKey(User,verbose_name='Usuario')
    status = models.BooleanField(default=1)

    def __unicode__(self):
        return u'%s'%self.fullname




class Customer(models.Model):
    class Meta:
        verbose_name = 'Cliente'

    c_fullname = models.CharField(u'Nombre Completo',max_length=250)
    birthdate = models.IntegerField(u'Año de nacimiento')
    contacto = models.TextField(blank=True,null=True)
    czipcode = models.CharField(u'c.p.',max_length=20)
    addr = models.CharField(u'Dirección',max_length=250)
    c_colonia = models.CharField(u'Colonia',max_length=200)
    c_delomun = models.CharField(u'Delegación/Municipio', max_length=200)
    c_state = models.CharField(u'Estado',max_length=200)
    seller_related = models.ForeignKey(Seller,blank=True,null=True)
    status = models.CharField(u'Status',max_length=20,choices=CUSTOMER_STATUS)
    date_create = models.DateTimeField(auto_now_add=True) 
    last_update = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '%s'%self.c_fullname



class Product(models.Model):
    class Meta:
        verbose_name = u'Producto'

    p_name = models.CharField(u'Producto',max_length=200)
    sales_point = models.ManyToManyField(SalesPoint)
    price = models.DecimalField(u'Precio',max_digits=12, decimal_places=2,null=True,blank=True)
    photo = models.ImageField(upload_to='product',blank=True,null=True)

    def __unicode__(self):
        return u'%s'%self.p_name

SALES_STATUS = (
                ('1','Proceso'),
                ('2','Concretada'),
                ('3','Cancelada'),
                ('4','Devolucion Producto')
                )

class Sale(models.Model):
    class Meta:
        verbose_name = u'Venta'

    sellerid = models.ForeignKey(Seller,verbose_name = 'Vendedor')
    sales_point_sale = models.ForeignKey(SalesPoint,verbose_name = 'Punto de Venta')
    customer_buy = models.ForeignKey(Customer, verbose_name = 'Comprador')
    product_saled = models.ForeignKey(Product)
    amount_sale = models.DecimalField(u'Cantidad',max_digits=20,decimal_places=2)
    quantity = models.IntegerField(u'Q',default=1)
    saledate = models.DateTimeField(auto_now = True)
    sale_status = models.CharField(max_length=20,choices = SALES_STATUS)
    
    def __unicode__(self):
        return u'%s %s %s'%(self.sellerid,self.customer_buy,self.product_saled)

sitio/views.py
# -*- encoding: utf-8 -*-
from django.http import HttpResponse
from django.template.context import RequestContext
from django.shortcuts import get_object_or_404, render_to_response,render
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import redirect
from django.contrib.auth import logout
import string as STrg
from django.db.models import Q
from salespoint.forms import * 
import datetime

ESTADOS = [(u'Aguascalientes', u'Aguascalientes'), (u'Baja California', u'Baja California'), (u'Baja California Sur', u'Baja California Sur'), (u'Campeche', u'Campeche'), (u'Chiapas', u'Chiapas'), (u'Chihuahua', u'Chihuahua'), (u'Coahuila de Zaragoza', u'Coahuila de Zaragoza'), (u'Colima', u'Colima'), (u'Distrito Federal', u'Distrito Federal'), (u'Durango', u'Durango'), (u'Guanajuato', u'Guanajuato'), (u'Guerrero', u'Guerrero'), (u'Hidalgo', u'Hidalgo'), (u'Jalisco', u'Jalisco'), (u'M\xe9xico', u'M\xe9xico'), (u'Michoac\xe1n de Ocampo', u'Michoac\xe1n de Ocampo'), (u'Morelos', u'Morelos'), (u'Nayarit', u'Nayarit'), (u'Nuevo Le\xf3n', u'Nuevo Le\xf3n'), (u'Oaxaca', u'Oaxaca'), (u'Puebla', u'Puebla'), (u'Quer\xe9taro', u'Quer\xe9taro'), (u'Quintana Roo', u'Quintana Roo'), (u'San Luis Potos\xed', u'San Luis Potos\xed'), (u'Sinaloa', u'Sinaloa'), (u'Sonora', u'Sonora'), (u'Tabasco', u'Tabasco'), (u'Tamaulipas', u'Tamaulipas'), (u'Tlaxcala', u'Tlaxcala'), (u'Veracruz de Ignacio de la Llave', u'Veracruz de Ignacio de la Llave'), (u'Yucat\xe1n', u'Yucat\xe1n'), (u'Zacatecas', u'Zacatecas')]



def years_to_cur():
    final = datetime.datetime.now().year
    inicio = datetime.datetime.now().year-100
    years = [(0,'----seleccione---')]
    for i in range(inicio,final):
        years.append((i,i),)
    return years

def logoff(request):
    logout(request)
    return redirect('/')


def index(request):
    context = RequestContext(request)
    return render_to_response("inicio.html",{},context)


def inicio(request):
    forma = FormCreator()
    modelo = Customer
    args={}
    widgets = {
                'birthdate':forms.Select(choices=years_to_cur()),
                'c_state':forms.Select(choices=ESTADOS,attrs={'class':'form-control'}),
                'c_delomun':forms.Select(),
                'c_colonia':forms.Select(),
                'zipcode':forms.Select()
              }
 
    forma = forma.advanced_form_to_model(modelo=Customer,widgets=widgets)

    # ARGS SECTION
    args['forma']=forma
    return render(request,'startpage.html',args)

sitio/templates/base2.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/chumbucket.css" %}" />
        <link href='http://fonts.googleapis.com/css?family=Quicksand:300,400,700' rel='stylesheet' type='text/css'>        
        <link href='http://fonts.googleapis.com/css?family=Muli:300,400,300italic|Montserrat:400,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/sitio.css" %}" />
         <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/animations.css" %}" />
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
        <script src="/static/js/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="{% static "js/site.js"%}"></script>
 
        {% block kuppe %}{% endblock %}

        <script type="text/javascript">
            $(document).ready(function(){
                $('.sender').submit(sendit);
                {% block document_ready %}
                {% endblock%}
                
            });
        </script>

    </head>
    <body>
   <div id="grandback"></div>
    <div id="gridback"></div>
    {% block content %}{% endblock %}

    </body>
</html>

sitio/templates/inicio.html
{% extends 'base2.html'%}

{% block document_ready %}
/*
if('21.8459332794'!='0.0' && '-102.271314158'!='0.0'){
            place  = new google.maps.LatLng(21.8459332794,-102.271314158);
            data = {
                      'name':'REDTRANET',
                      'location':place,
                      'icon':'contact.png'
                 }
            locations.push(data);
        }
        var geocoder = new google.maps.Geocoder();
        geocoder.geocode({'address':'Mexico'},function(results,status){
        if(status==google.maps.GeocoderStatus.OK){
            the_place = locations[0].location;
            //new google.maps.LatLng(results[0].geometry.location.k, results[0].geometry.location.B);
            draw_map();
            map.zoom=9;
            map.center=locations[0].location;
        }    
        else{
            alert('some problem with maps');
        }
        });
    */
{% endblock%}
{% block content %}
    <div id="boxmaster">
        <a name="home"></a>
        <div id="brandbox" class="inline_blocke">
             <div class="inline_blocke">
                <h2 id="brandtxt">Client manager</h2>
                <h1 id="brandname">SalesPoint</h1>
            </div>
            <br/>
                <div id="login-box" class="inline_blocke">
                    <form  name="login_form" action="login" method="post" class="sender">
                    {%csrf_token%}
                        <div>
                            <label></label>
                            <input type="text" name="user" class="inputtext" placeholder="Usuario" /> 
                        </div>
                         <div>
                            <label></label>
                            <input type="password" name="pass" class="inputtext" placeholder="Contraseña" /> 
                        </div>
                        <button type="submit" class="fa fa-sign-in loginin" ></button>
                    </form>
                </div>
        </div>

    </div>


{% endblock %}

sitio/templates/startpage.html
{% extends 'base2.html'%}
{% block content %}
    <div id="boxmaster">
        <ul>
            <li class="inline_blocke"><p>Hello: {{user.seller_set.all.0.fullname}}</p></li>
            <li class="inline_blocke"><a href="/logout">logouts</a></li>
        </ul>
    

    <div id="form-box">
                    <form  name="customer_form" action="/customerform" method="post" class="sender forma">
                    {%csrf_token%}
                    {{forma.as_p}}
                       <button type="submit" class="fa fa-sign-in loginin" ></button>
                    </form>

    </div>

    </div> 
{% endblock %} 