d4contacts/appcontact/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import *

urlpatterns = patterns('appcontact.views',
    url(r'^$','index',name='index'),
    url(r'^contacto$','contact_form',name='contact_form'),
    url(r'^inicio$','inicio',name='inicio'),
    url(r'^logout$','logoff',name='logoff'),
    url(r'^mycontacts','mycontacts',name='mycontacts'),
    url(r'^detailcontact/(?P<idc>\d+)/$','detailcontact',name='detailcontact'),
    url(r'^edtcontact/(?P<idc>\d+)/$','edtcontact',name='edtcontact'),
    url(r'^delcontact/(?P<idc>\d+)/$','delcontact',name='delcontact'),
    url(r'^resultados$','resultados',name='resultados'),

)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += patterns('appcontact.restviews',
    url(r'^login$','login',name='login'),
    url(r'^addcontact$','addcontact',name='addcontact'),
    url(r'^addphoto$','addphoto',name='addphoto'),
    url(r'^delphoto/(?P<idu>\d+)/$','delphoto',name='delphoto'),
    url(r'^location$','restlocation',name='restlocation'),
    url(r'^addtag/$','addtag',name='addtag'),
    url(r'^delnote$','delnote',name='delnote'),
    url(r'^colonia$','colonia',name='colonia'),
    url(r'^addnote$','addnote',name='addnote'),
    url(r'^deltag$','deltag',name='deltag'),
    url(r'^cps$','cps',name='cps'),
    
)

d4contacts/contactmanager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('appcontact.urls')),
    (r'^', include('appentity.urls')),
    (r'^', include('tasks.urls')),
    url(r'^admin/',include(admin.site.urls)),        
)

salespoint/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('sitio.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

sitio/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import *

urlpatterns = patterns('sitio.views',
                    url(r'^$','index',name='index'),
                    #url(r'^contacto$','contact_form',name='contact_form'),
                    url(r'^inicio$','inicio',name='inicio'),
                    url(r'^logout$','logoff',name='logoff'),
                    #url(r'^mycontacts','mycontacts',name='mycontacts'),
                    #url(r'^detailcontact/(?P<idc>\d+)/$','detailcontact',name='detailcontact'),
                    #url(r'^edtcontact/(?P<idc>\d+)/$','edtcontact',name='edtcontact'),
                    #url(r'^delcontact/(?P<idc>\d+)/$','delcontact',name='delcontact'),
                    #url(r'^resultados$','resultados',name='resultados'),
             ) 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += patterns('sitio.restviews',
    url(r'^login$','login',name='login'),
    #url(r'^addcontact$','addcontact',name='addcontact'),
    #url(r'^addphoto$','addphoto',name='addphoto'),
    #url(r'^delphoto/(?P<idu>\d+)/$','delphoto',name='delphoto'),
    #url(r'^location$','restlocation',name='restlocation'),
    #url(r'^addtag/$','addtag',name='addtag'),
    #url(r'^delnote$','delnote',name='delnote'),
    #url(r'^colonia$','colonia',name='colonia'),
    #url(r'^addnote$','addnote',name='addnote'),
    #url(r'^deltag$','deltag',name='deltag'),
    #url(r'^cps$','cps',name='cps'),
    
)

d4contacts/appcontact/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import simplejson
from tasks.models import *

class ContactFiles(models.Model):
    type_file = models.CharField(max_length=200,blank=True)
    contact_file = models.FileField(upload_to='ContactFiles')
    '''
        status params 
         case 0 incomplete
         case 1 Complete
         case 2 Deleted
    '''
class Contact(models.Model):
    userrelated = models.ForeignKey(User,null=True,blank=True)
    usercreator = models.IntegerField(null=True,blank=True)
    namec = models.CharField(u'Nombre(s) ',max_length=200)
    lastname = models.CharField(u'Apellido(s)',max_length=200,blank=True,null=True)
    chargec = models.CharField(u'Cargo',max_length=100,blank=True,null=True)
    date_create = models.DateTimeField(default=datetime.now,auto_now_add=True)
    status = models.CharField(max_length=2,default=1)
    estado = models.CharField(u'Estado',max_length=200)
    delomun = models.CharField(u'Del./Municipio',max_length=200)
    colonia = models.CharField(u'Colonia',max_length=200)
    cp = models.CharField(u'C.P.',max_length=10,blank=True,null=True,default=100)
    address = models.CharField(u'Dirección',max_length=200,blank=True,null=True,default=' ')
    lon = models.FloatField(default=0)
    lat = models.FloatField(default=0)
    extrac = models.TextField(blank=True,null=True)
    photoc = models.IntegerField(blank=True,null=True)
    tags = models.TextField(blank=True,null=True)

    def photoimg(self):
        try: 
            photoim = ContactFiles.objects.get(pk=self.photoc)
        except: 
            photoim = None
        return photoim

    def tages(self):
        if self.tags:
            tags = simplejson.loads(self.tags)
            listing = tags
        else:
            listing = None
        return listing

    def mytasks(self):
        t = None #Tasking.objects.filter(asigned_string='contact',asignedto=self.pk)
        return t
    
    def __unicode__(self):
        return u'%s'%self.namec

    def social(self):
        return self.metacontact_set.filter(asignetstring='redsocial')

    def contacto(self):
        tels = self.metacontact_set.filter(asignetstring='contact',metastring__icontains='Tel')
        fones = []
        for t in tels:
            metavalue = t.metavalue.replace('|',' ')
            fones.append({'metastring':t.metastring,'metavalue':metavalue})
        return fones

    def addresses(self):
        return self.metacontact_set.filter(asignetstring='direccion')


class MetaContact(models.Model):
    asignetstring = models.CharField(max_length=200)
    asignetto = models.IntegerField()
    metastring = models.CharField(max_length=200)
    metavalue = models.CharField(max_length=200)
    contact_meta = models.ForeignKey(Contact)




class EmailList(models.Model):
    contacto = models.ForeignKey(Contact)
    email = models.EmailField(unique=True)
    typeofemail = models.CharField(max_length=10,blank=True)


class Tag(models.Model):
    tagname = models.CharField(max_length=200,null=True,default='Untitle')
    def __unicode__(self):
        if self.tagname:
            return '%s' %(self.tagname[0].upper())
    
class Sepomex(models.Model):
    codigo_postal = models.CharField(max_length=5)
    asentamiento = models.CharField(max_length=250)
    tipo_asentamiento = models.CharField(max_length=100)
    municipio = models.CharField(max_length=250)
    estado = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=250)
    descripcion_codigo_postal = models.CharField(max_length=5)
    clave_estado = models.CharField(max_length=2)
    clave_oficina = models.CharField(max_length=5)
    clave_tipo_asentamiento = models.CharField(max_length=5)
    clave_municipio = models.CharField(max_length=3)
    clave_asentamiento = models.CharField(max_length=2)
    zona = models.CharField(max_length=40)
    clave_ciudad = models.CharField(max_length=2)

class Note(models.Model):
    class Meta:
        ordering = ['date_create']
    
    text = models.TextField(default='untitle')
    sender = models.ForeignKey(User)
    receptor = models.ForeignKey(Contact)
    date_create = models.DateField(auto_now_add=True,default=datetime.now)


TYPES = (('option','option'),
         ('open','text'),
        )
class ExtraFields(models.Model):
    fieldname = models.CharField(u'Nombre del campo',max_length=200)
    typefield = models.CharField(u'Tipo de campo',max_length=200,choices=TYPES)
    ordering = models.IntegerField(default=1)
    
    def __unicode__(self):
        return '%s'%self.fieldname

class OptionFields(models.Model):
    fieldp = models.ForeignKey(ExtraFields)
    optiontxt = models.CharField(u'Opción',max_length=200)

    def __unicode__(self):
        return u'%s'%self.optiontxt

d4contacts/appentity/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
import simplejson
from appcontact.models import Contact


class EntityFile(models.Model):
    type_file = models.CharField(max_length=200,blank=True)
    entity_file = models.FileField(upload_to='entityFiles')
    '''
        status params 
         case 0 incomplete
         case 1 Complete
         case 2 Deleted
    
    '''

class Entity(models.Model):
    user = models.ForeignKey(User)
    nameac = models.CharField(u'Nombre Org.',max_length=200)
    emailacoount = models.CharField(u'Email',max_length=100,blank=True)
    url = models.CharField(u'Web',max_length=200,blank=True,null=True)
    extra = models.TextField(blank=True,null=True)
    photoa = models.IntegerField(blank=True,null=True)
    date_create = models.DateTimeField(auto_now_add=True)
    cpac = models.CharField(u'C.P.',max_length=20,null=True,blank=True)
    lonac = models.FloatField(default=0,blank=True,null=True)
    latac = models.FloatField(default=0,blank=True,null=True)
    estadoa = models.CharField(u'Estado',max_length=200)
    delomun = models.CharField(u'Del/Municipio',max_length=200)
    colonia = models.CharField(u'Colonia',max_length=200)
    tags = models.TextField(blank=True,null=True)

    def photoimg(self):
        photoim = EntityFile.objects.get(pk=self.photoa)
        return photoim

    def mysocial(self):
        myc = self.metaentity_set.filter(asignetstring='redsocial')
        return myc

    def myaddrs(self):
        myc = self.metaentity_set.filter(asignetstring='direccion')
        return myc

    def tages(self):
        if self.tags:
            l = simplejson.loads(self.tags)
        else:
            l = None
        return l
    def __unicode__(self):
        return u'%s' % self.nameac


class EntitySocialInfo(models.Model):
    entity_id = models.ForeignKey(Entity)
    social_accounts = models.TextField()

class MetaEntity(models.Model):
    asignetstring = models.CharField(max_length=200)
    asignetto = models.IntegerField()
    metastring = models.CharField(max_length=200)
    metavalue = models.CharField(max_length=200)
    contact_meta = models.ForeignKey(Entity)




class As_Contact(models.Model):
    asociation = models.ForeignKey(Entity)
    contacto = models.ForeignKey(Contact)
    date_create = models.DateTimeField(auto_now=True)
 

d4contacts/appcontact/templates/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/chumbuket.css" %}" />
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/sitio.css" %}" />
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
       <script type="text/javascript" src="{% static "js/jquery-1.11.1.min.js"%}"></script>
        <script type="text/javascript" src=""></script>
        {% block kuppe %}{% endblock %}
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>

d4contacts/appcontact/templates/detailcontact.html
{% extends 'base2.html'%}
{% load staticfiles %}
{% load tasker%}

{% block kuppe %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "bootstrap/css/timepicker.css" %}" />
    <script type="text/javascript" src= "/static/bootstrap/js/timepicker.js"></script>
    <script type="text/javascript" src= "/static/js/tasks.js"></script>
    <script type="text/javascript" src= "/static/js/chumbukcet.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script type="text/javascript" src="{% static "js/geolocalizations.js" %}"></script>
    <script type="text/javascript" src="{% static "bootstrap/js/bootstrap.js" %}"></script>
    <script type="text/javascript">
        var locations = [];
            if('{{c.lat}}'!='0.0' && '{{c.lon}}'!='0.0'){
                place  = new google.maps.LatLng({{c.lat}},{{c.lon}});
                data = {
                    'name':'{{c.namec}}',
                    'location':place,
                    'icon':'contact.png'
                }
                locations.push(data);
            }
            else
            {
                var geocoder = new google.maps.Geocoder();
                var country  = 'Mexico';
                address = country;
                geocoder.geocode({'address':address},function(results,status){
                    if(status==google.maps.GeocoderStatus.OK){
                        var the_place = new google.maps.LatLng(results[0].geometry.location.k, results[0].geometry.location.B);
                        /*
                        $('#map_canvas').html('Cargando mapa, porfavor espere...');
                        $('#id_lat').val(results[0].geometry.location.k);
                        $('#id_lon').val(results[0].geometry.location.B);
                        $('#id_latac').val(results[0].geometry.location.k);
                        $('#id_lonac').val(results[0].geometry.location.B);
                        initialize(the_place);
                        $('#map-canvas').removeClass('blind');
                        */
                        data = {
                            'name':'{{c.namec}}',
                            'location':the_place,
                            'icon':'contact.png'
                        }
                        locations.push(data);
                    }    
                    else{
                        alert('some problem with maps');    
                    }
                });
            }

        var the_place = null;
        var map;

    $(document).ready(function(){
        var geocoder = new google.maps.Geocoder();
        geocoder.geocode({'address':'Mexico'},function(results,status){
            if(status==google.maps.GeocoderStatus.OK){
                the_place = locations[0].location;
                //new google.maps.LatLng(results[0].geometry.location.k, results[0].geometry.location.B);
                draw_map();
                map.zoom=9;
                map.center=the_place;

            }    
            else{
                alert('some problem with maps');    
            }
        });

        $('.showtask').click(tasker);
        $('#tagform').submit(ajax_send_tag);
        $('.showtagform').click(function(){
            var mia = $(this).position();
            $('#popover0').show().css('top',(mia.top+35)+'px').css('left',(mia.left-45)+'px');    
            
        });
        
        $('.ajaxcall').click(ajaxcall);
        $('.editor_open').click(editor_open); 
    });
</script>
{% endblock %}

{% block content %}


<div role="tooltip" class="popover  bottom in" id="popover0">
    <div class="arrow"></div>
        <h3 class="popover-title">Agregar Tag</h3>
            <div class="popover-content">
            <div class="arrow"></div>
            <div  class=" phateris" id="tagerbox">
                <div class="arrow"></div>
                <form  method="post" class="tagger" id="tagform">
                    {%csrf_token%}
                    <input type="text" name="tag"  class="inline_blocke form-control" style="width:67%;"/>
                    <input type="hidden" name="contactpk" value="{{c.pk}}" />
                    <input type="submit" class="btn btn-success" value="Agregar" />
                </form>
            </div>
    </div>
</div>


<div class="table_n">
    <div class="table_r white_box">
        <div style="width:70%;"  class="table_c detailleft">
            <div class="layout_box">
                <div class="inline_blocke">
                    {% if c.photoimg.contact_file.url %}
                    <div class="inline_blocke singlefoto" style="background-image:url(/static/{{c.photoimg.contact_file.url}});">
                    <span class="inline_blocke">&nbsp;</span></div>
                    {% else %}
                        <img src="/static/images/nophoto.png" />
                    {% endif %}
                </div>
                <div class="inline_blocke info_list_contact">
                    <h2 class="title-names">{{c.namec}} {{c.lastname}}</h2>
                    <div class="t4b">{{c.chargec}}</div>
                    <div>
                        <a href="#" class="showtagform t5b">Agregar etiquetas</a>
                    </div>
                </div>
                    <div id="tage_boxe">
                        {% for t in c.tages %}
                        <div class="inline_blocke tags">
                            <a href="#{{t}}" id="pice_{{c.pk}}" class="inline_blocke removetagg glyphicon glyphicon-remove">&nbsp;</a>
                            <div class="inline_blocke t7">{{t}}</div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="layout_box">
                    <div class="tabs">
                       <ul class="nav nav-tabs" role="tablist">
                            <li class="active"><a href="#">Notas</a></li>
                            <!-- <li class="blind"><a href="#">Email</a></li>-->
                        </ul>
                    </div>
                    <div>
                        <form action="/addnote" method="post" id="addnotes">
                        <div class="t5" style="margin:9px 3px;">Agregar una nota <!-- acerca de {{c.namec}} --></div>
                        <textarea name="text" class="borderme form-control"> </textarea>
                        {%csrf_token%}
                        <input type="hidden" name="sender" value="{{user.pk}}" />
                        <input type="hidden" name="receptor" value="{{c.pk}}" />
                         <div class="alineador">
                         <input type="submit" value="Agregar nota" class="btn btn-success" />
                        </div>
                        </form>
                    </div>
                    <div class="notes_box">
                        {%for note in c.note_set.all|dictsort:"date_create" reversed %}
                        <div class="notes_list">
                            <div class="right_text">
                                <a href="/delnote?id={{note.pk}}" class="inline_blocke glyphicon glyphicon-remove ajaxcall"></a>
                            </div>
                            <div class="inline_blocke table_c" style="padding:1px 6px;"><img src="/static/images/sobre.gif" /></div>
                            <div class="inline_blocke table_c">
                                <div class="t6 fecha_s">{{note.date_create}}</div>
                                <div><a href="#editnote/{{note.pk}}" class="glyphicon glyphicon-pencil editor_open"></a></div>
                                <div class="t7">Nota de <span class="sender">{{note.sender.contact_set.all.0.namec}}
                                    {{note.sender.contact_set.all.0.lastname}}</span>
                                </div>
                                <p class="t6 text txt_mode">{{note.text}}</p>
                                <div class="edit_mode blind">
                                    <input type="hidden" name="idnote" value="{{note.pk}}" />
                                    <textarea name="textnote">{{note.text}}</textarea>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="notes_list blind"> 
                             <div class="right_text">
                                <a href="/delnote?id={{note.pk}}" class="inline_blocke glyphicon glyphicon-remove ajaxcall"></a>
                            </div>
                            <div class="inline_blocke table_c" style="padding:1px 6px;"><img src="/static/images/sobre.gif" /></div>
                            <div class="inline_blocke table_c">
                                <div class="t6 fecha_s"></div>
                                <div class="t7">Nota de <span class="sender"></span>
                                </div>
                                <p class="t6 text"></p>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
       <div id="" class="table_c graybox">
            <div class="table_n" style="height:40px;width:98%;margin.auto;">
                <div class="table_r">
                    <div class="table_c" style="text-align:left;">
                        <p class="contact_editor_lnk"><a href="/edtcontact/{{c.pk}}/" class="linker">Editar Persona</a></p>  
                    </div>
                    <div class="table_c" style="text-align:right;">
                        <a href="/delcontact/{{c.pk}}/" class="linker deleteperson">Eliminar Persona</a>
                    </div>
                </div>
            </div>
            
            <div class="table_n greenbox">
                <div class="table_r">
                    <p class="table_c" style="text-align:left;padding-right:18px;">
                        <a href="#/calendar/newtask/"  data-toggle="modal" data-target="#myModal" style="color:#FFF;">+ Agregar Tarea</a>
                    </p>
        
                </div> 
        </div>
            {% include "pices/tareas.html"%} 
           <br/>
           <div class="greenbox" style="height:24px;"></div>
           <ul class="contact_info_box">
                {% for s in c.contactsocialinfo_set.all %}
                <li class="t5"> Twitter: {{s.cuentas.account}}</li>
                {% endfor %}
                {% if c.emaillist_set.all%}
                <li class="t5">Email(s)</li>
                {% endif %}
                {% for m in c.emaillist_set.all %}
                <li><a href="mailto:{{m.email}}" class="linker_blue">{{m.email}}</a></li>
                {% endfor %}
                {% if c.contacto %}
                <li class="t5">Teléfono(s)</li>
                {% for tel  in c.contacto %}
                <li><span class="t4 right_contact">{{tel.metastring}}</span><span class="t5 right_contact"> {{tel.metavalue}}</span></li>
                {% endfor %} 
                {% endif%}
                <li>
                    <div>
                        <div class="t5">Localización</div>
                       {% for adr in c.addresses%}
                        <div class="t4 right_contact">
                            <span class="t4 right_contact">{{adr.metavalue}}</span>
                        </div>
                        {% endfor %}
                        <div class="t4 right_contact"><span class="t5">Colonia:</span> {{c.colonia}}</div>
                        <div class="t4 right_contact"><span class="t5">Delegación o Municipio:</span> {{c.delomun}}</div>
                        <div class="t4 right_contact"><span class="t5">Estado:</span> {{c.estado}}</div>
                        <div class="t4 right_contact"><span class="t5">C.P.:</span>{{c.cp}}</div>
                    </div>
                    <div id="map_canvas" style="width:100%;height:200px;border-radius:20px;"></div>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

d4contacts/appcontact/templates/menu_left.html
<div id="logo_box">
    <span id="logo" class="inline_blocke"><img src="/static/images/logohome.jpg" /></span>
<!--    <a href="/" class="inline_blocke"><img src="/static/images/btn_home.jpg" /></a>
    <div class="inline_blocke lnk_ms" style="text-align:right;">
        <a href="#btn" class="inline_blocke red_round">2</a>
    </div>
-->
</div>

<div id="user_info_box">
    <div class="inline_blocke" id="photo_home" style="margin:5% 0px;background:url(/static/{{user.contact_set.all.0.photoimg.contact_file.url}}) no-repeat;background-size:cover;">
    </div>
    <div class="inline_blocke name_box">
        <h4 class="salute">Bienvenido</h4>
        <div class="myname">{{user.contact_set.all.0.namec}}</div>
        <div class="myname">{{user.contact_set.all.0.lastname}}</div>
    </div>
</div>
<ul id="left_menu">
    <li><a href="/" class="inline_blocke"><span class="fa fa-home iconic"></span><span>Bienvenido</span></a></li>
    <li class="blind"><a href="#" class="inline_blocke"><img src="/static/images/l2.png" />Actividad Reciente</a></li>
    <li>
        <a href="/mycontacts" class="inline_blocke"><span class="fa fa-user iconic"></span>Contacto</a>
    </li>
    <li>
        <a href="/myentities"><span class="fa fa-users iconic"></span>Organización</a>
    </li>
    <li><a href="#" ><span class="fa fa-check iconic"></span>Tareas</a></li>
     <li class="blind"><a href="#"><img src="/static/images/l5.png" />Buscador > </a></li>
</ul>
<div id="reciente" style="display:none;">
    <div class="hdt" style="padding-bottom:5px;">&nbsp;&nbsp;VISTO RECIENTE&nbsp;&nbsp;</div>
    <ul>
        <li>
            <img src="/static/images/nophoto.jpg" height="33px">
            <div class="inline_blocke">
                <div class="name_left">This is his name</div>
                <div class="text_left">This is his charge</div>
            </div>
        </li>
         <li>
            <img src="/static/images/nophoto.jpg" height="33px">
            <div class="inline_blocke">
                <div class="name_left">This is his name</div>
                <div class="text_left">This is his charge</div>
            </div>
        </li>
       <li>
            <img src="/static/images/nophoto.jpg" height="33px">
            <div class="inline_blocke">
                <div class="name_left">This is his name</div>
                <div class="text_left">This is his charge</div>
            </div>
        </li>
    </ul>
 </div> 

d4contacts/appcontact/templates/mycontacts.html
{% extends 'base2.html'%}
{% load tager %}
{% load staticfiles %}


{% block kuppe %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/contacts.css" %}" />
    <script type="text/javascript" src="{% static "js/validations.js" %}"></script>
    <script type="text/javascript" src="{% static "js/contacts.js" %}"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script type="text/javascript" src="{% static "js/geolocalizations.js" %}"></script>
 

    <script type="text/javascript">
        var locations = [];
        {% for c in contacts %}
            if('{{c.lat}}'!='0.0' && '{{c.lon}}'!='0.0'){
                place  = new google.maps.LatLng({{c.lat}},{{c.lon}});
                data = {
                    'id':'{{c.pk}}',
                    'name':'{{c.namec}}',
                    'location':place,
                    'icon':'contact.png'
                }
                locations.push(data);
            }

        {% endfor%}
        var the_place = null;
        var map;

function chowmap(){
        if(map){
            nothingtodo=true;
        }
        else{
            var geocoder = new google.maps.Geocoder();
            geocoder.geocode({'address':'Mexico'},function(results,status){
            if(status==google.maps.GeocoderStatus.OK){
                the_place = new google.maps.LatLng(results[0].geometry.location.k, results[0].geometry.location.B);
                draw_map();
            }    
            else{
                alert('some problem with maps');    
            }
            });
        }
   
}

$(document).ready(function(){
    $('[href=#map_canvas]').click(chowmap);    

        $('.tagger').click(tagger);

        $('.removetagg').click(removetag);
});
</script>
{% endblock %}


{% block content %}
<div class="table_n">
    <div class="table_r white_box">
            <div id="layout_box" class="table_c">
                <h2 class="title-2">Mis Contactos</h2>
                {% include 'forms/search_form.html'%}
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li class="active"><a href="#list_results" role="tab" data-toggle="tab">Listado</a></li>
                    <li><a href="#map_canvas" role="tab" data-toggle="tab">Mapa</a></li>
                </ul>
                <br/>
                <div class="tab-content">
                    <ul id="list_results" class="tab-pane fade in active">
                        {% for c in contacts %}
                        <li>
                            <div class="inline_blocke boxy">&nbsp;</div>
                            {% if c.photoc %}
                            <div class="inline_blocke myminiphoto" style="background-image:url(/static/{{c.photoimg.contact_file.url}});">
                                <a href="/detailcontact/{{c.pk}}/" class="inline_blocke" style="width:100%;height:100%;">&nbsp;</a>
                            </div>
                            {% else %}
                             <div class="inline_blocke myminiphoto" style="background-image:url(/static/images/nophoto.png);">
                            </div>
                            {% endif %}
                            <div class="inline_blocke" style="width:80%;">
                                <a href="/detailcontact/{{c.pk}}/" class="t4">
                                <div>{{c.namec}} {{c.lastname}}</div>
                                {% for c in c.contacto %}
                                <div class="t5">{{c.metastring}} {{c.metavalue}}</div>
                                {% endfor %}
                                {% for m in c.emaillist_set.all %}
                                <div class="t5">{{m.email}}</div>
                                {% endfor %}
                                {% for adr in c.addresses %}
                                <div class="t5">{{adr.metavalue}}</div>
                                {% endfor %}
                                </a>
                                 {% for asoc in c.as_contact_set.all %}
                                <div class="t4"><a href="/detailentity/{{asoc.asociation.pk}}">{{asoc.asociation.nameac}}</a></div>
                                {% endfor%}
                                <div class="tag_block">
                                  {% for a in c.tages %}
                                        <span class="inline_blocke tags">{{a}}</span>
                                    {% endfor%}
                                </div>
                            </div>
                       </li>
                        {% endfor %}
                    </ul>
                    <div id="map_canvas"  class="tab-pane fade" style="width:100%;height:400px;border-radius:20px;"></div>
                </div>
            </div>
            <div class="tablec">{% include 'pices/tags.html' %}</div>

    </div>
</div>



{% endblock %}