d4contacts/appcontact/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import *

urlpatterns = patterns('appcontact.views',
    url(r'^$','index',name='index'),
    url(r'^contacto$','contact_form',name='contact_form'),
    url(r'^inicio$','inicio',name='inicio'),
    url(r'^logout$','logoff',name='logoff'),
    url(r'^mycontacts','mycontacts',name='mycontacts'),
    url(r'^detailcontact/(?P<idc>\d+)/$','detailcontact',name='detailcontact'),
    url(r'^edtcontact/(?P<idc>\d+)/$','edtcontact',name='edtcontact'),
    url(r'^delcontact/(?P<idc>\d+)/$','delcontact',name='delcontact'),
    url(r'^resultados$','resultados',name='resultados'),

)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += patterns('appcontact.restviews',
    url(r'^login$','login',name='login'),
    url(r'^addcontact$','addcontact',name='addcontact'),
    url(r'^addphoto$','addphoto',name='addphoto'),
    url(r'^delphoto/(?P<idu>\d+)/$','delphoto',name='delphoto'),
    url(r'^location$','restlocation',name='restlocation'),
    url(r'^addtag/$','addtag',name='addtag'),
    url(r'^delnote$','delnote',name='delnote'),
    url(r'^colonia$','colonia',name='colonia'),
    url(r'^addnote$','addnote',name='addnote'),
    url(r'^deltag$','deltag',name='deltag'),
    url(r'^cps$','cps',name='cps'),
    
)

d4contacts/contactmanager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('appcontact.urls')),
    (r'^', include('appentity.urls')),
    (r'^', include('tasks.urls')),
    url(r'^admin/',include(admin.site.urls)),        
)

salespoint/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('sitio.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

sitio/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import *

urlpatterns = patterns('sitio.views',
                    url(r'^$','index',name='index'),
                    #url(r'^contacto$','contact_form',name='contact_form'),
                    url(r'^inicio$','inicio',name='inicio'),
                    url(r'^logout$','logoff',name='logoff'),
                    #url(r'^mycontacts','mycontacts',name='mycontacts'),
                    #url(r'^detailcontact/(?P<idc>\d+)/$','detailcontact',name='detailcontact'),
                    #url(r'^edtcontact/(?P<idc>\d+)/$','edtcontact',name='edtcontact'),
                    #url(r'^delcontact/(?P<idc>\d+)/$','delcontact',name='delcontact'),
                    #url(r'^resultados$','resultados',name='resultados'),
             ) 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += patterns('sitio.restviews',
    url(r'^login$','login',name='login'),
    #url(r'^addcontact$','addcontact',name='addcontact'),
    #url(r'^addphoto$','addphoto',name='addphoto'),
    #url(r'^delphoto/(?P<idu>\d+)/$','delphoto',name='delphoto'),
    #url(r'^location$','restlocation',name='restlocation'),
    #url(r'^addtag/$','addtag',name='addtag'),
    #url(r'^delnote$','delnote',name='delnote'),
    #url(r'^colonia$','colonia',name='colonia'),
    #url(r'^addnote$','addnote',name='addnote'),
    #url(r'^deltag$','deltag',name='deltag'),
    #url(r'^cps$','cps',name='cps'),
    
)

d4contacts/appcontact/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import simplejson
from tasks.models import *

class ContactFiles(models.Model):
    type_file = models.CharField(max_length=200,blank=True)
    contact_file = models.FileField(upload_to='ContactFiles')
    '''
        status params 
         case 0 incomplete
         case 1 Complete
         case 2 Deleted
    '''
class Contact(models.Model):
    userrelated = models.ForeignKey(User,null=True,blank=True)
    usercreator = models.IntegerField(null=True,blank=True)
    namec = models.CharField(u'Nombre(s) ',max_length=200)
    lastname = models.CharField(u'Apellido(s)',max_length=200,blank=True,null=True)
    chargec = models.CharField(u'Cargo',max_length=100,blank=True,null=True)
    date_create = models.DateTimeField(default=datetime.now,auto_now_add=True)
    status = models.CharField(max_length=2,default=1)
    estado = models.CharField(u'Estado',max_length=200)
    delomun = models.CharField(u'Del./Municipio',max_length=200)
    colonia = models.CharField(u'Colonia',max_length=200)
    cp = models.CharField(u'C.P.',max_length=10,blank=True,null=True,default=100)
    address = models.CharField(u'Dirección',max_length=200,blank=True,null=True,default=' ')
    lon = models.FloatField(default=0)
    lat = models.FloatField(default=0)
    extrac = models.TextField(blank=True,null=True)
    photoc = models.IntegerField(blank=True,null=True)
    tags = models.TextField(blank=True,null=True)

    def photoimg(self):
        try: 
            photoim = ContactFiles.objects.get(pk=self.photoc)
        except: 
            photoim = None
        return photoim

    def tages(self):
        if self.tags:
            tags = simplejson.loads(self.tags)
            listing = tags
        else:
            listing = None
        return listing

    def mytasks(self):
        t = None #Tasking.objects.filter(asigned_string='contact',asignedto=self.pk)
        return t
    
    def __unicode__(self):
        return u'%s'%self.namec

    def social(self):
        return self.metacontact_set.filter(asignetstring='redsocial')

    def contacto(self):
        tels = self.metacontact_set.filter(asignetstring='contact',metastring__icontains='Tel')
        fones = []
        for t in tels:
            metavalue = t.metavalue.replace('|',' ')
            fones.append({'metastring':t.metastring,'metavalue':metavalue})
        return fones

    def addresses(self):
        return self.metacontact_set.filter(asignetstring='direccion')


class MetaContact(models.Model):
    asignetstring = models.CharField(max_length=200)
    asignetto = models.IntegerField()
    metastring = models.CharField(max_length=200)
    metavalue = models.CharField(max_length=200)
    contact_meta = models.ForeignKey(Contact)




class EmailList(models.Model):
    contacto = models.ForeignKey(Contact)
    email = models.EmailField(unique=True)
    typeofemail = models.CharField(max_length=10,blank=True)


class Tag(models.Model):
    tagname = models.CharField(max_length=200,null=True,default='Untitle')
    def __unicode__(self):
        if self.tagname:
            return '%s' %(self.tagname[0].upper())
    
class Sepomex(models.Model):
    codigo_postal = models.CharField(max_length=5)
    asentamiento = models.CharField(max_length=250)
    tipo_asentamiento = models.CharField(max_length=100)
    municipio = models.CharField(max_length=250)
    estado = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=250)
    descripcion_codigo_postal = models.CharField(max_length=5)
    clave_estado = models.CharField(max_length=2)
    clave_oficina = models.CharField(max_length=5)
    clave_tipo_asentamiento = models.CharField(max_length=5)
    clave_municipio = models.CharField(max_length=3)
    clave_asentamiento = models.CharField(max_length=2)
    zona = models.CharField(max_length=40)
    clave_ciudad = models.CharField(max_length=2)

class Note(models.Model):
    class Meta:
        ordering = ['date_create']
    
    text = models.TextField(default='untitle')
    sender = models.ForeignKey(User)
    receptor = models.ForeignKey(Contact)
    date_create = models.DateField(auto_now_add=True,default=datetime.now)


TYPES = (('option','option'),
         ('open','text'),
        )
class ExtraFields(models.Model):
    fieldname = models.CharField(u'Nombre del campo',max_length=200)
    typefield = models.CharField(u'Tipo de campo',max_length=200,choices=TYPES)
    ordering = models.IntegerField(default=1)
    
    def __unicode__(self):
        return '%s'%self.fieldname

class OptionFields(models.Model):
    fieldp = models.ForeignKey(ExtraFields)
    optiontxt = models.CharField(u'Opción',max_length=200)

    def __unicode__(self):
        return u'%s'%self.optiontxt

d4contacts/appcontact/templates/forms/cform.html
{% extends extend  %}

{% load staticfiles %}
{% load bootstrap_tags %}

{% block kuppe %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/contacts.css" %}" />
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script type="text/javascript" src="{% static "js/geo.js" %}"></script>
    <script type="text/javascript" src="{% static "js/contacts.js" %}"></script>
    <script type="text/javascript">
        data_colonia = {'estado':$('#id_estado').val()};
        params_to_dropdowns = [{'changer':'#id_estado','victim':'#id_delomun','url':'/location','param':'pk'},
                               {'changer':'#id_delomun','victim':'#id_colonia','url':'/colonia','param':'pk'},
                               {'changer':'#id_colonia','victim':'#id_cp','url':'/cps','param':'pk','data':data_colonia}

                      ];

        
        $.fn.cli = function(){
            alert('a');    
        }
        
        $(document).ready(function(){
           changers(params_to_dropdowns);    
           $('.adder').click(addli);
           $('.deler').click(rmli);
           $('.ajax_send').submit(sendit);
        });
    </script>
 
{% endblock %}

{% block content %}
{% load tager%}
<div class="form_box">
    <h2 class="title-1">{% if idc %}Agregando nuevo{% else %} Editando {% endif %} Contacto</h2>
    <form name="addcontact" id="addcontact"  method="post" action="/addcontact" enctype="multipart/form-data"  class="ajax_send">
           {%csrf_token%}
           <input type="hidden" name="id" id="id"  value="{{idc}}" />
           <input type="hidden" name="photoc" id="photoc" value=""  />
           
           <div class="col-md-9 left_form">
                <ul class="field-list">
                    <li>
                        <label class="inline_blocke" for="id_namec"> {{forma.namec.label}} </label>
                        {{forma.namec|addcss:"form-control inline_blocke field-meddium"}}
                    </li>
                    <li>
                        <label class="inline_blocke" for="id_lastname"> {{forma.lastname.label}} </label>
                        {{forma.lastname|addcss:"form-control inline_blocke field-meddium"}}
                    </li>
                   <li>
                        <label class="inline_blocke" for="id_chargec"> {{forma.chargec.label}} </label>
                        {{forma.chargec|addcss:"form-control inline_blocke field-meddium"}}
                    </li>
                    <li>
                         <label class="inline_blocke" for="id_organizacion"> Organización </label>
                        {{forma.chargec|addcss:"form-control inline_blocke field-meddium"}}
                    </li>

                </ul>
           </div>
           <div class="col-md-3" style="padding:9px 0px;">
                <a href="#/addphoto" class="btn btn-success" style="width:100%;">Seleccionar imagen</a>
                <div style="border-radius:90px;margin-top:7px;">
                    <img src="/static/images/nophoto.png"/>
                </div>
           </div>
            <ul>

                        {% for cfor in cform %}
               <li>
               <div class="col-md-9 left_form">
                            <label class="inline_blocke">Contacto</label>
                            {{cfor.typeof|addcss:"form-control inline_blocke field-short"}}
                            {{cfor.contactinfo|addcss:"form-control inline_blocke field-short"}}
               </div>
               
               <div class="col-md-3 rboxy field-list">
                            {{cfor.whereis|addcss:"form-control inline_blocke field-right-d"}}
                            <a href="#add" class="adder fright inline_blocke glyphicon glyphicon-plus-sign"></a>
                            <a href="#remover" class="deler fright inline_blocke glyphicon glyphicon-remove-sign blind"></a>
               </div>
               </li>

                        {% endfor %}          
            </ul>
            <ul>            
            {% for cfor in cform %}
               <li>
               <div class="col-md-9 left_form">
                            <label class="inline_blocke">Red Social</label>
                            {{cfor.redsociallist|addcss:"form-control inline_blocke field-meddium"}}
               </div>
               
               <div class="col-md-3 rboxy field-list">
                            {{cfor.redsocial|addcss:"form-control inline_blocke field-right-d"}}
                            <a href="#add" class="adder fright inline_blocke glyphicon glyphicon-plus-sign"></a>
                            <a href="#remover" class="deler fright inline_blocke glyphicon glyphicon-remove-sign blind"></a>
               </div>
               </li>
            {% endfor %}          
               </ul>
               <ul>
               <li>
               <div class="col-md-9 left_form">
                        {% for cfor in cform %}
                            <label class="inline_blocke">Dirección</label>
                            {{cfor.direccion|addcss:"form-control inline_blocke field-meddium"}}
                        {% endfor %}          
               </div>
               
               <div class="col-md-3 rboxy field-list">
                         {% for cfor in cform %}
                            {{cfor.whereisdir|addcss:"form-control inline_blocke field-right-d"}}
                            <a href="#add" class="adder fright inline_blocke glyphicon glyphicon-plus-sign"></a>
                            <a href="#remover" class="deler fright inline_blocke glyphicon glyphicon-remove-sign blind"></a>
                        {% endfor %}          
               </div>
               </li>
            </ul>
            <div style="clear:both;text-align:left;">
                <label style="width:15.5%;" class="inline_blocke">&nbsp;</label>
                <div class="inline_blocke  short">
                    <label for="id_estado"> {{forma.estado.label}} </label>
                    {{forma.estado|addcss:"form-control"}}
                </div>
                <div class="inline_blocke  short">
                    <label for="id_delomun"> {{forma.delomun.label}} </label>
                    {{forma.delomun|addcss:"form-control"}}
                </div>

               <div class="inline_blocke short">
                    <label for="id_colonia"> {{forma.colonia.label}} </label>
                    {{forma.colonia|addcss:"form-control"}}
                </div>

               <div class="inline_blocke short">
                    <label for="id_cp"> {{forma.cp.label}} </label>
                    {{forma.cp|addcss:"form-control"}}
                </div>

            </div>
            <div style="text-align:left;margin:12px 0px;">
                <label for="id_extrac" style="width:100%;">Información Extra (biografía,notas,comó conoció la Organización)</label>
                {{forma.extrac|addcss:"form-control small-f"}}
            
                <div>
                    ¿Quién puede ver este contacto?
                </div>
                <ul>
                    <li>
                        <input type="radio" name="who" value="t"  class="inline_blocke" />
                        <span class="inline_blocke spacing_r">Todos</span>
                    </li>
                    <li>
                        <input type="radio" name="who" value="me" class="inline_blocke" />
                        <span class="inline_blocke spacing_r">Solo yo</span> 
                    </li>
                    <li>
                        <input type="radio" name="who" value="select" class="inline_blocke" />
                        <span class="inline_nblocke spacing_r">Seleccionar gente...</span>
                    </li>
                </ul>
            
            </div>
                {{forma.lon}}{{forma.lat}}


            <ul class="blind">
                <li>
                    <div class="inline_blocke" style="width:80%;">
                        <label>Tags</label>
                        <input type="text" name="tags" class="form-control inline_blocke selector" />
                    </div>

                    <div class="inline_blocke" style="padding-top:5%;">
                        <a href="#add" class="adder glyphicon glyphicon-plus-sign">&nbsp;</a>&nbsp;&nbsp;
                        <a href="#remover" class="deler  glyphicon glyphicon-remove-sign">&nbsp;</a>
                    </div>
                </li>
            </ul>

           {% if extraform %}
                {{extraform|as_bootstrap}}
            <hr/>
            {% endif %}
            
            <div style="text-align:left;margin:10px 0px;">
                <input  id="btn_save" type="submit" value="+Agregar" class="btn btn-success"/>
                 o <a href="/mycontacts">Reestablecer</a>
            </div>
            <br/>
        </form>
</div>
{% endblock %}

d4contacts/appcontact/templates/forms/eform.html
{% extends extend  %}
{% load staticfiles %}
{% load bootstrap_tags %}
{% block kuppe %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/contacts.css" %}" />
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script type="text/javascript" src="{% static "js/geo.js" %}"></script>
    <script type="text/javascript" src="{% static "js/contacts.js" %}"></script>
    <script type="text/javascript">
        data_colonia = {'estado':$('#id_estado').val()};
        params_to_dropdowns = [{'changer':'#id_estado','victim':'#id_delomun','url':'/location','param':'pk'},
                               {'changer':'#id_delomun','victim':'#id_colonia','url':'/colonia','param':'pk'},
                               {'changer':'#id_colonia','victim':'#id_cp','url':'/cps','param':'pk','data':data_colonia}
                      ];
       
        $(document).ready(function(){
           
            changers(params_to_dropdowns);    
            $( ".combobox").combobox({select:function(){
                $(this).change();    
            }
            
            });
            $('.adder').click(addli);
            $('.deler').click(rmli);
            $('.ajax_send').submit(sendit);
            $('#addphoto').click(submitPhoto);
            $('#contact_file').change(submitPhoto);
            $('#id_colonia').change(localizeme);
            {% if idc %}localizeme();{% endif%}
        });
    </script>
{% endblock %}
{% block content %}
{% load tager%}
<div class="form_box">
    <h2 class="title-1"> Contacto</h2>
    <form name="addcontact" id="addcontact"  method="post" action="/addcontact" enctype="multipart/form-data"  class="ajax_send">
           {%csrf_token%}
           <input type="hidden" name="id" id="id"  value="{{idc}}" />
           <input type="file" name="contact_file" id="contact_file" value=""  style="display:none;" /> 
           {% if idc %}
                {{forma.userrelated}}
                {{forma.usercreator}}
            {% endif %}
           <div class="col-md-9 left_form">
               <ul class="field-list">
                    <li>
                        <label class="inline_blocke" for="id_namec"> {{forma.namec.label}} </label>
                        {{forma.namec|addcss:"form-control inline_blocke field-meddium"}}
                    </li>
                    <li>
                        <label class="inline_blocke" for="id_lastname"> {{forma.lastname.label}} </label>
                        {{forma.lastname|addcss:"form-control inline_blocke field-meddium"}}
                    </li>
                   <li>
                        <label class="inline_blocke" for="id_chargec"> {{forma.chargec.label}} </label>
                        {{forma.chargec|addcss:"form-control inline_blocke field-meddium"}}
                    </li>
                    <li class="blind">
                         <label class="inline_blocke" for="id_organizacion"> Organización </label>
                    </li>

                </ul>
           </div>
           <div class="col-md-3" style="padding:9px 0px;">
                <a href="#/addphoto" id="addphoto" class="btn btn-success" style="width:100%;">Seleccionar imagen</a>
                <div class="rounding">
                    {% if photo%}
                        <img src="/static/{{photo}}" class="myphoto" />
                    {% else %}
                        <img src="/static/images/nophoto.png" class="myphoto"/>
                    {% endif %}
                </div>
           </div>
            <ul>
               {% for cfor in cform %}
               <li>
                   <div class="col-md-9 left_form">
                                <label class="inline_blocke">Contacto</label>
                                {{cfor.typeof|addcss:"form-control inline_blocke field-short"}}
                                {{cfor.contactinfo|addcss:"form-control inline_blocke field-short"}}
                   </div>
                   <div class="col-md-3 rboxy field-list">
                                {{cfor.whereis|addcss:"form-control inline_blocke field-right-d"}}
                                {% include 'pices/botones.html'%}
                   </div>
               </li>
               {% endfor %}          


               {% for cfor in emailform %}
               <li>
                   <div class="col-md-9 left_form">
                                <label class="inline_blocke">Contacto</label>
                                {{cfor.typeof|addcss:"form-control inline_blocke field-short"}}
                                {{cfor.contactinfo|addcss:"form-control inline_blocke field-short"}}
                   </div>
                   
                   <div class="col-md-3 rboxy field-list">
                                {{cfor.whereis|addcss:"form-control inline_blocke field-right-d"}}
                                {% include 'pices/botones.html'%}
                   </div>
               </li>
               {% endfor %}          




            </ul>
            <ul>            
            {% for rsfor in rsform %}
               <li>
               <div class="col-md-9 left_form">
                            <label class="inline_blocke">Red Social</label>
                            {{rsfor.redsociallist|addcss:"form-control inline_blocke field-meddium"}}
               </div>
               
               <div class="col-md-3 rboxy field-list">
                            {{rsfor.redsocial|addcss:"form-control inline_blocke field-right-d"}}
                            {% include 'pices/botones.html'%}
              </div>
               </li>
            {% endfor %}          
               </ul>
               <ul>
               {% for addfor in addsform %}
               <li>
               <div class="col-md-9 left_form">
                            <label class="inline_blocke">Dirección</label>
                            {{addfor.direccion|addcss:"form-control inline_blocke field-meddium"}}
               </div>
               
               <div class="col-md-3 rboxy field-list">
                            {{addfor.whereisdir|addcss:"form-control inline_blocke field-right-d"}}
                            {% include 'pices/botones.html'%}
                </div>
               </li>
               {% endfor %}
            </ul>
            <div style="clear:both;text-align:left;">
                <label style="width:15.5%;" class="inline_blocke">&nbsp;</label>
                <div class="inline_blocke short">
                    <label for="id_estado"> {{forma.estado.label}} </label>
                    {{forma.estado|addcss:"form-control combobox"}}
                </div>
                <div class="inline_blocke  short">
                    <label for="id_delomun"> {{forma.delomun.label}} </label>
                    {{forma.delomun|addcss:"form-control combobox"}}
                </div>
                <br/>
                <label style="width:15.5%;" class="inline_blocke">&nbsp;</label>
               <div class="inline_blocke short">
                    <label for="id_colonia"> {{forma.colonia.label}} </label>
                    {{forma.colonia|addcss:"form-control combobox"}}
                </div>

               <div class="inline_blocke short">
                    <label for="id_cp"> {{forma.cp.label}} </label>
                    {{forma.cp|addcss:"form-control combobox"}}
                </div>

            </div>
            <div style="text-align:left;margin:12px 0px;">
                <label for="id_extrac" style="width:100%;">Información Extra (biografía,notas,comó conoció la Organización)</label>
                {{forma.extrac|addcss:"form-control small-f"}}
           <!-- 
                <div>
                    ¿Quién puede ver este contacto?
                </div>
                <ul>
                    <li>
                        <input type="radio" name="who" value="t"  class="inline_blocke" />
                        <span class="inline_blocke spacing_r">Todos</span>
                    </li>
                    <li>
                        <input type="radio" name="who" value="me" class="inline_blocke" />
                        <span class="inline_blocke spacing_r">Solo yo</span> 
                    </li>
                    <li>
                        <input type="radio" name="who" value="select" class="inline_blocke" />
                        <span class="inline_nblocke spacing_r">Seleccionar gente...</span>
                    </li>
                </ul>
            -->
            
            </div>
                {{forma.lon}}{{forma.lat}}{{forma.photoc}}


            <ul class="blind">
                <li>
                    <div class="inline_blocke" style="width:80%;">
                        <label>Tags</label>
                        <input type="text" name="tags" class="form-control inline_blocke selector" />
                    </div>

                    <div class="inline_blocke" style="padding-top:5%;">
                        <a href="#add" class="adder glyphicon glyphicon-plus-sign">&nbsp;</a>&nbsp;&nbsp;
                        <a href="#remover" class="deler  glyphicon glyphicon-remove-sign">&nbsp;</a>
                    </div>
                </li>
            </ul>
            <div id="map-canvas" class="blind" style="z-index:1;height:300px;width:100%;"></div>
           {% if extraform %}
                {{extraform|as_bootstrap}}
            <hr/>
            {% endif %}
            
            <div style="text-align:left;margin:10px 0px;">
                <input  id="btn_save" type="submit" value="+Agregar" class="btn btn-success"/>
                 o <a href="/mycontacts">Reestablecer</a>
            </div>
            <br/>
        </form>
</div>
{% endblock %}

d4contacts/appcontact/templates/forms/search_form.html
<div class="blind">
    <span class="inline_blocke">Busca por:&nbsp;&nbsp;</span>
    <a href="#searchnamec" class="chowinput inline_blocke">Nombre &nbsp;</a>
    <a href="#searchemail" class="chowinput inline_blocke">eMail &nbsp;</a>
    <a href="#searchlocation" class="chowinput inline_blocke">Localización &nbsp;</a>
</div>
<br/>
<div id="boxy_float" class="blind apaca">
    <div id="closer_box">
        <a href="#boxy_float" class="closer inline_blocke glyphicon glyphicon-remove">&nbsp;</a>
    </div>
    <form id="search_form" method="post" action="/resultados">
        {%csrf_token%}
        {% for t in tags %}
        <div id="searchtag" class="{% if not t %}blindi {% endif%} tab_s inline_blocke">
            <span>Tag: {{t}}</span><input type="text" name="tag"  value="{{t}}" />
        </div>
        {% endfor %}
        <input type="hidden" name="words" value="{{form.words}}" />
        <input type="hidden" name="page" value="1" />
    
        <div id="searchnamec" class="{% if not formdata.namec%}blind{% endif %} inline_blocke tab_s">
            Nombre: <input type="text" name="namec" class="form-control" id="namec" value="{{formdata.namec}}" />
        </div>
        <div id="searchemail" class="{% if not formdata.email %} blind{% endif %} inline_blocke tab_s">
            Email: &nbsp;&nbsp;&nbsp;&nbsp;<input type="text" id="email" class="form-control"  name="email" value="{{formdata.email}}" />
        </div>
        <div id="searchlocation" class="{% if not formdata.estado %}blind{% endif  %} inline_blocke tab_s">
            <div>
                Estado:&nbsp; <select name="estado" id="estado" class="locatio_drop form-control">
                    <option value=""> seleccione estado</option>
                    {% for s in location.0 %}
                    <option value="{{s.estado}}" {% ifequal s.estado formdata.estado %} 
                    selected="slected" {% endifequal %}>{{s.estado}}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <span id="tomunicipio">Ciudad:</span> <select name="delomun" id="delomun" class="form-control">
                    <option value="">seleccione una opción</option>
                    {% for c in location.1 %}
                    <option value="{{c.municipio}}" {% ifequal formdata.delomun c.municipio%} 
                    selected="selected"{% endifequal%} >{{c.municipio}}</option>
                    {% endfor %}
                </select>
            </div>
    
        </div>
        <input type="submit"  id="buscando" class="btn_green inline_blocke" value="Buscar"/>
    </form>
</div>

<ul id="search_breadcrubs">
    {% if tags %}
    <li>Tags:</li>
    {% endif %}
    {% for t in tags%}
        <li class='inline_blocke'>
            <a href="#tag_{{t}}" class="removetagg glyphicon glyphicon-remove-sign">&nbsp;</a>    
            <span class="inline_blocke">{{t}}</span>
        </li>
    {% endfor %}
    {% if formdata.namec%}
    <li>Nombre:</li>
    <li class="inline_blocke">
        <a href="#namec" class="removetagg glyphicon glyphicon-remove-sign">&nbsp;</a>    
        <span class="inline_blocke">{{formdata.namec}}</span>
    </li>
    {% endif %}
    {% if formdata.estado%}
    <li>Estado:</li>
    <li class="inline_blocke">
        <a href="#estado" class="removetagg glyphicon glyphicon-remove-sign">&nbsp;</a>    
        <span class="inline_blocke">{{formdata.estado}}</span>
    </li>
    {% endif %}

   {% if formdata.delomun%}
   <li>Municipio:</li>
    <li class="inline_blocke">
        <a href="#delomun" class="removetagg glyphicon glyphicon-remove-sign">&nbsp;</a>    
        <span class="inline_blocke">{{formdata.delomun}}</span>
    </li>
    {% endif %}

   {% if formdata.email%}
   <li>Email:</li>
    <li class="inline_blocke">
        <a href="#email" class="removetagg glyphicon glyphicon-remove-sign">&nbsp;</a>    
        <span class="inline_blocke">{{formdata.email}}</span>
    </li>
    {% endif %}


</ul>
<br/><br/>